---
- hosts: test
  remote_user: root
  gather_facts: false
  tasks:
    - name: 'apt-get update'
      apt:
        update_cache: yes
    - name: Install 'ack-grep' package
      apt:
        name: ack-grep
        state: latest
    - name: Install 'git' package
      apt:
        name: git
        state: latest
    - name: Install 'htop' package
      apt:
        name: htop
        state: latest
    - name: Install 'tmux' package
      apt:
        name: tmux
        state: latest
    - name: Install 'tree' package
      apt:
        name: tree
        state: latest
    - name: Install 'vim' package
      apt:
        name: vim
        state: latest
    - name: Installing 'software-properties-common' for 'tmate'
      apt:
        name: software-properties-common
        state: latest
    - name: Adding 'ppa:tmate.io/archive' repo for 'tmate'
      apt_repository:
        repo: ppa:tmate.io/archive
    - name: Installing 'tmate'
      apt:
        name: tmate
        state: latest
